### ISSUE TITLE
Cannot find module './src/ClickToComponent' or its corresponding type declarations

### ISSUE THREAD

**Issue by stephanepx** [ericclemmons/click-to-component#65]
Hi ! 
I'm working with TS 4.5.5, and I have this TS error just after installing the module :
`Cannot find module './src/ClickToComponent' or its corresponding type declarations`
Do you know why this error appears ?
(I try with latest TS version)
Thanks!

**Comment by stephanepx** [comment]
I found this issue already closed : https://github.com/ericclemmons/click-to-component/issues/40
But it seems that release is not ready yet 
Thanks!
